env:
  AZURE_SUB_UAT: '8e9001ef-d089-4768-b516-ae4be3e68dde'
  


on:
  schedule:
  #   #Start 
     - cron: '25 5 * * 1-5'
  workflow_dispatch:

name: Apps-start-uat
jobs:  

  Spring-App-start:
    runs-on: ubuntu-latest
    environment: azure-polaris-uat-start-stop-automation
    steps:
    - uses: actions/checkout@main
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_POLARIS_UAT_START_STOP_SERVICE_PRINCIPAL }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.48.0
        inlineScript: |
              az config set extension.use_dynamic_install=yes_without_prompt
              az configure --defaults group='rg-springapps' spring='spring-polaris-uat-uksouth'
              az spring start --name 'spring-polaris-uat-uksouth' --resource-group 'rg-springapps' --subscription ${{ env.AZURE_SUB_UAT }}

  App-Service-start:
    runs-on: ubuntu-latest
    environment: azure-polaris-uat-start-stop-automation
    steps:
    - uses: actions/checkout@main
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_POLARIS_UAT_START_STOP_SERVICE_PRINCIPAL }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.48.0
        inlineScript: |
              az config set extension.use_dynamic_install=yes_without_prompt
              az webapp start --name 'as-app-directus-polaris-uat-uksouth' --resource-group 'rg-directus' --subscription ${{ env.AZURE_SUB_UAT }}  

  Function-App-start:
    runs-on: ubuntu-latest
    environment: azure-polaris-uat-start-stop-automation
    steps:
    - uses: actions/checkout@main
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_POLARIS_UAT_START_STOP_SERVICE_PRINCIPAL }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.48.0
        inlineScript: |
              az config set extension.use_dynamic_install=yes_without_prompt
              az functionapp start --name 'as-app-malwarescan-polaris-uat-uksouth' --resource-group 'rg-malwarescanning' --subscription ${{ env.AZURE_SUB_UAT }}  
