env:
  AZURE_SUB_TST: 'f00e932c-2dc9-4eed-83ab-28bee4d9dbb3'
  resourcegrouplocation: './Polaris/Polaris-RG/polaris-rg-create.bicep'
  paramlocation: './Polaris/Polaris-RG/polaris-rg-tst-parm.json'
  


on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Polaris/Polaris-RG/polaris-rg-create.bicep
      - Polaris/Polaris-RG/polaris-rg-tst-parm.json

name: Resoucegroup_deployment_TST
jobs:  
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run bicep linter
        run: az bicep build --file ${{ env.resourcegrouplocation }}       
  validate: 
    runs-on: ubuntu-latest
    environment: azure-devops-code-validation
    steps: 
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_DEVOPS_CODE__VALIDATION_SERVICE_PRINCIPAL }}
    - uses: azure/arm-deploy@v1
      name: Run preflight validation
      with:
        scope: subscription
        subscriptionId: ${{ env.AZURE_SUB_TST }}
        template: ${{ env.resourcegrouplocation }}
        parameters: ${{ env.paramlocation }}
        region: 'uksouth'
        failOnStdErr: false 
        deploymentMode: validate
      
  build_deploy_rg_TST:
    needs: [lint, validate]
    runs-on: ubuntu-latest
    environment: azure-polaris-test
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_POLARIS_TEST_SERVICE_PRINCIPAL }}

      # Dev Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ env.AZURE_SUB_TST }}
        template: ${{ env.resourcegrouplocation }}
        parameters: ${{ env.paramlocation }}
        region: 'uksouth'
        failOnStdErr: false 

