env:
  AZURE_SUB_PROD: '95ca7646-ed92-470e-9dfb-23f25093d507'
  AZURE_SUB_TST: 'f00e932c-2dc9-4eed-83ab-28bee4d9dbb3'
  AZURE_SUB_UAT: '8e9001ef-d089-4768-b516-ae4be3e68dde'
  AZURE_SUB_TRN: '28949f95-bda6-4716-a7f7-3b13b40d1301'


  adflocation: './Polaris/Polaris-Data-Factory/polaris-data-factory.bicep'
  prodparamlocation: './Polaris/Polaris-Data-Factory/polaris-data-factory-prod.json'
  testparamlocation: './Polaris/Polaris-Data-Factory/polaris-data-factory-test.json'
  uatparamlocation: './Polaris/Polaris-Data-Factory/polaris-data-factory-uat.json'
  trnparamlocation: './Polaris/Polaris-Data-Factory/polaris-data-factory-trn.json'
  
  
  

# on: [workflow_dispatch]
on:
  workflow_dispatch:
    inputs:
      select:
        type: choice
        description: Pipeline to deploy
        options:
          - Data_Factory_Prod 
          - Data_Factory_Test 
          - Data_Factory_UAT
          - Data_Factory_TRN

name: Datafactory_deployment
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run bicep linter
        run: az bicep build --file ${{ env.adflocation }}

  validate: 
    runs-on: ubuntu-latest
    environment: azure-devops-code-validation
    steps: 
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_DEVOPS_CODE__VALIDATION_SERVICE_PRINCIPAL }}
    - uses: azure/arm-deploy@v1
      name: Run preflight validation
      with:
        scope: subscription
        subscriptionId: ${{ env.AZURE_SUB_TST }}
        template: ${{ env.adflocation }}
        parameters: ${{ env.testparamlocation }}
        region: 'uksouth'
        failOnStdErr: false 
        deploymentMode: validate


  build_deploy_adf_PROD:
    needs: [lint, validate ]
    if: inputs.select == 'Data_Factory_Prod'
    runs-on: ubuntu-latest
    environment: azure-polaris-production
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_POLARIS_PROD_SERVICE_PRINCIPAL }}
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ env.AZURE_SUB_PROD }}
        template: ${{ env.adflocation }}
        parameters: ${{ env.prodparamlocation }}
        region: 'uksouth'
        failOnStdErr: false

  build_deploy_adf_TST:
    needs: [lint, validate ]
    if: inputs.select == 'Data_Factory_Test'
    runs-on: ubuntu-latest
    environment: azure-polaris-test
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_POLARIS_TEST_SERVICE_PRINCIPAL }}
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ env.AZURE_SUB_TST }}
        template: ${{ env.adflocation }}
        parameters: ${{ env.testparamlocation }}
        region: 'uksouth'
        failOnStdErr: false

  build_deploy_adf_UAT:
    needs: [lint, validate ]
    if: inputs.select == 'Data_Factory_UAT'
    runs-on: ubuntu-latest
    environment: azure-polaris-uat
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_POLARIS_UAT_SERVICE_PRINCIPAL }}
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ env.AZURE_SUB_UAT }}
        template: ${{ env.adflocation }}
        parameters: ${{ env.uatparamlocation }}
        region: 'uksouth'
        failOnStdErr: false 

  build_deploy_adf_TRN:
    needs: [lint, validate ]
    if: inputs.select == 'Data_Factory_TRN'
    runs-on: ubuntu-latest
    environment: azure-polaris-training
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_POLARIS_TRN_SERVICE_PRINCIPAL }}
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ env.AZURE_SUB_TRN }}
        template: ${{ env.adflocation }}
        parameters: ${{ env.trnparamlocation }}
        region: 'uksouth'
        failOnStdErr: false 

