env:
  AZURE_SUB_TST: 'f00e932c-2dc9-4eed-83ab-28bee4d9dbb3'
  foundationlocation: './Polaris/Polaris-Foundation/polaris-foundation.bicep'
  paramlocation: './Polaris/Polaris-Foundation/polaris-foundation-tst-param.json'
  

# on: [workflow_dispatch]
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Polaris/Polaris-Foundation/polaris-foundation.bicep
      - Polaris/Polaris-Foundation/polaris-foundation-tst-param.json

name: Foundation_deployment_TST
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run bicep linter
        run: az bicep build --file ${{ env.foundationlocation }}
  validate: 
    runs-on: ubuntu-latest
    environment: azure-devops-code-validation
    steps: 
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_DEVOPS_CODE__VALIDATION_SERVICE_PRINCIPAL }}
    - uses: azure/arm-deploy@v1
      name: Run preflight validation
      with:
        scope: subscription
        subscriptionId: ${{ env.AZURE_SUB_TST }}
        template: ${{ env.foundationlocation }}
        parameters: ${{ env.paramlocation }}
        region: 'uksouth'
        failOnStdErr: false 
        deploymentMode: validate


  build_whatif_foundation_TST:
    needs: [lint, validate]
    runs-on: ubuntu-latest
    environment: azure-devops-code-validation
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_DEVOPS_CODE__VALIDATION_SERVICE_PRINCIPAL }}
    - name: what-if
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ env.AZURE_SUB_TST }}
        template: ${{ env.foundationlocation }}
        parameters: ${{ env.paramlocation }}
        region: 'uksouth'
        failOnStdErr: false 
        additionalArguments: --what-if

  build_deploy_foundation_TST:
    needs: [lint, validate, build_whatif_foundation_TST]
    runs-on: ubuntu-latest
    environment: azure-polaris-test
    steps:

      # Checkout code
    - uses: actions/checkout@v3

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_POLARIS_TEST_SERVICE_PRINCIPAL }}
    - name: Install latest version of Bicep
      shell: sh
      run: |
          # From https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/install#linux
          # Fetch the latest Bicep CLI binary
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          # Mark it as executable
          chmod +x ./bicep
          # Add bicep to your PATH (requires admin)
          sudo mv ./bicep /usr/local/bin/bicep
          # Verify you can now access the 'bicep' command
          bicep --help
          # Done!

      # Dev Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ env.AZURE_SUB_TST }}
        template: ${{ env.foundationlocation }}
        parameters: ${{ env.paramlocation }}
        region: 'uksouth'
        failOnStdErr: false 

