
on:
  issues:
    types: [opened]

name: Jira Ticket Bug

jobs:
  Createticket:
    name: Create Bug
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: https://reedglobal.atlassian.net
        JIRA_USER_EMAIL: alex.hunte@reed.com
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}


    - name: Create
      id: jira
      uses: tomhjp/gh-action-jira-create@v0.1.3
      with:
        project: IAC
        issuetype: "Bug"
        summary: "${{ github.event.issue.title }} - Issue #${{ github.event.issue.number }}"
        description: "${{ github.event.issue.body }}\n\nCreated from GitHub Action"
        # extraFields: '{"fixVersions": [{"name": "TBD"}]}'

          
      env:
        JIRA_BASE_URL: https://reedglobal.atlassian.net
        JIRA_USER_EMAIL: alex.hunte@reed.com
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Log created issue
      run: echo "Issue ${{ steps.jira.outputs.issue }} was created"

    - name: Log html
      run: echo "Issue ${{ github.event.issue.html_url }}  was created"

    - name: Comment on GitHub issue
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          ${{ steps.jira.outputs.issue }}