env:
  AZURE_SUB_TRN: '28949f95-bda6-4716-a7f7-3b13b40d1301'
  networklocation: './Polaris/Polaris-Networking/polaris-networking.bicep'
  paramlocation: './Polaris/Polaris-Networking/Polaris-network-trn.parm.json'
  

on:
  workflow_dispatch:
    branches:
      - main 
    inputs:
      tag:
        description: "Tag to apply to main branch"
        required: true


name: network_deployment_TRN
jobs:
  create-release-candidate:
    runs-on: ubuntu-latest
    env:
      # release-artifacts-upload-filespec: build-artifacts/artifact.txt
      unique-tag-name: ${{ inputs.tag }}-releasecandidate-${{ github.run_id }}-${{ github.run_attempt }}
    outputs:
      release-id: ${{ steps.create-release.outputs.id }}
    steps:
      - name: Create release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.unique-tag-name }}
          tag_name: ${{ env.unique-tag-name }}
          generate_release_notes: true
          draft: false
          prerelease: true
          # files: ${{ env.release-artifacts-upload-filespec }}

  validate: 
    needs: [create-release-candidate]
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    environment: azure-devops-code-validation
    steps: 
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_DEVOPS_CODE__VALIDATION_SERVICE_PRINCIPAL }}
    - uses: azure/arm-deploy@v1
      name: Run preflight validation
      with:
        scope: subscription
        subscriptionId: ${{ env.AZURE_SUB_TRN }}
        template: ${{ env.networklocation }} 
        parameters: ${{ env.paramlocation }} 
        region: 'uksouth'
        failOnStdErr: false 
        deploymentMode: validate
  lint:
    needs: [create-release-candidate]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run bicep linter
        run: az bicep build --file ${{ env.networklocation }}

  build_whatif_network_TRN:
    needs: [lint, validate]
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    environment: azure-devops-code-validation
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_DEVOPS_CODE__VALIDATION_SERVICE_PRINCIPAL }}
    - name: what-if
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ env.AZURE_SUB_TRN }}
        template: ${{ env.networklocation }} 
        parameters: ${{ env.paramlocation }} 
        region: 'uksouth'
        failOnStdErr: false 
        additionalArguments: --what-if

  build_deploy_network_TRN:
    needs: [lint, validate, build_whatif_network_TRN]
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    environment: azure-polaris-training
    steps:

      # Checkout code
    - uses: actions/checkout@v3

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_POLARIS_TRN_SERVICE_PRINCIPAL }}

      # Dev Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ env.AZURE_SUB_TRN }}
        template: ${{ env.networklocation }} 
        parameters: ${{ env.paramlocation }} 
        region: 'uksouth'
        failOnStdErr: false 
